[package]
name = "bin"
version.workspace = true
edition.workspace = true
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sandbox = { path = "../sandbox" }
migrator = { path = "../migrator" }
server = { path = "../server" }

clap = { version = "4.3", features = ["derive"] }
serde_json = "1.0"
shadow-rs = "0.23.0"
tokio = { version = "1.31.0", features = ["full"] }

[build-dependencies]
shadow-rs = "0.23.0"
