[package]
name = "sandbox"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
tempfile = "3.3.0"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["jobapi2","processthreadsapi","handleapi","memoryapi","synchapi","psapi"] }
windows = { version = "0.48.0", features = ["System", "System_Diagnostics"] }