[package]
name = "sandbox"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
tempfile = "3.3.0"
