[package]
name = "server_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["parsing", "full", "extra-traits"] }
quote = "1.0"

[dev-dependencies]
actix-web = "4"
