[workspace]

members = [
    "cli",
    "contest",
    "judger",
    "passwd",
    "problem",
    "sandbox", 
    "sandbox_macro", 
    "server",
    "server_derive",
    "store",
    "store_derive",
    "tools",
    "serde_ts_typing",
    "serde_ts_typing_derive",
    "migrator"
]

[workspace.package]
authors = ["ZROJ Team"]
edition = "2021"
keywords = ["Online Judge", "Sandbox"]
version = "0.1.0"
