[workspace]

members = [
    "sandbox", 
    "tools",
    "contest",
    "problem",
    "server",
    "judger",
    "cli",
    "passwd",
    "macros"
]

[workspace.package]
authors = ["ZROJ Team"]
edition = "2021"
keywords = ["Online Judge", "Sandbox"]
version = "0.1.0"
