[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
store_derive = { path = "../store_derive" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"