[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
test = false
bench = false

[dependencies]
actix-web = "4"
server = { path="../server" }
env_logger = "0.10.0"