// generated by server/src/bin/gen_docs.rs
// DO NOT EDIT.

import type { AsyncData } from "nuxt/app";
import type { FetchError } from "ofetch";

function callAPI(method: string, path: string, args?: any): Promise<any> {
    if (process.client) {
        console.log('client call api', method, path, args)
    }
    path = useRuntimeConfig().public.apiBase + path;

    const options = {
        server: false, // 这只会降低首次加载的体验
        key: method + ":" + path,
        method: method as any,
        credentials: 'include' as any,
        headers: useRequestHeaders()
    };
    if (args === undefined) {
        return useFetch(path, options);
    } else if (method === 'get') {
        return useFetch(path, { ...options, query: args });
    } else if (args instanceof FormData) {
        return useFetch(path, { ...options, body: args});
    } else {
        return useFetch(path, { ...options, body: args });
    }
}
export type AlignKind = (AlignKindCenter|AlignKindLeft|AlignKindNone|AlignKindRight);
export type AlignKindCenter = "center";
export type AlignKindLeft = "left";
export type AlignKindNone = "none";
export type AlignKindRight = "right";
export type AuthInfoRes = {email:string;username:Username;};
export type BlockQuote = {children:Node[];};
export type Break = {};
export type Code = {lang:(null|string);meta:(null|string);value:string;};
export type Definition = {identifier:string;label:(null|string);title:(null|string);url:string;};
export type Delete = {children:Node[];};
export type Elapse = number;
export type Emphasis = {children:Node[];};
export type FileDescriptor = ("Stdin"|"Stdout"|{Named:string;});
export type FootnoteDefinition = {children:Node[];identifier:string;label:(null|string);};
export type FootnoteReference = {identifier:string;label:(null|string);};
export type FullDataMetaQuery = {id:number;};
export type GravatarInfo = {email:string;no_cache:(null|boolean);};
export type Heading = {children:Node[];depth:number;};
export type Html = {value:string;};
export type IOKind = ("StdIO"|{FileIO:{input:FileDescriptor;output:FileDescriptor;};});
export type Image = {alt:string;title:(null|string);url:string;};
export type ImageReference = {alt:string;identifier:string;label:(null|string);reference_kind:ReferenceKind;};
export type InlineCode = {value:string;};
export type InlineMath = {value:string;};
export type Link = {children:Node[];title:(null|string);url:string;};
export type LinkReference = {children:Node[];identifier:string;label:(null|string);reference_kind:ReferenceKind;};
export type List = {children:Node[];ordered:boolean;spread:boolean;start:(null|number);};
export type ListItem = {checked:(null|boolean);children:Node[];spread:boolean;};
export type LoginPayload = {passwordHash:string;username:Username;};
export type Math = {meta:(null|string);value:string;};
export type Memory = number;
export type MetasQuery = {max_count:number;max_id:(null|number);min_id:(null|number);pattern:(null|string);};
export type Node = (NodeBlockQuote|NodeBreak|NodeCode|NodeDefinition|NodeDelete|NodeEmphasis|NodeFootnoteDefinition|NodeFootnoteReference|NodeHeading|NodeHtml|NodeImage|NodeImageReference|NodeInlineCode|NodeInlineMath|NodeLink|NodeLinkReference|NodeList|NodeListItem|NodeMath|NodeParagraph|NodeRoot|NodeStrong|NodeTable|NodeTableCell|NodeTableRow|NodeText|NodeThematicBreak|NodeToml|NodeTwoColumns|NodeYaml);
export type NodeBlockQuote = (BlockQuote&{type:"blockquote";});
export type NodeBreak = (Break&{type:"break";});
export type NodeCode = (Code&{type:"code";});
export type NodeDefinition = (Definition&{type:"definition";});
export type NodeDelete = (Delete&{type:"delete";});
export type NodeEmphasis = (Emphasis&{type:"emphasis";});
export type NodeFootnoteDefinition = (FootnoteDefinition&{type:"footnoteDefinition";});
export type NodeFootnoteReference = (FootnoteReference&{type:"footnoteReference";});
export type NodeHeading = (Heading&{type:"heading";});
export type NodeHtml = (Html&{type:"html";});
export type NodeImage = (Image&{type:"image";});
export type NodeImageReference = (ImageReference&{type:"imageReference";});
export type NodeInlineCode = (InlineCode&{type:"inlineCode";});
export type NodeInlineMath = (InlineMath&{type:"inlineMath";});
export type NodeLink = (Link&{type:"link";});
export type NodeLinkReference = (LinkReference&{type:"linkReference";});
export type NodeList = (List&{type:"list";});
export type NodeListItem = (ListItem&{type:"listItem";});
export type NodeMath = (Math&{type:"math";});
export type NodeParagraph = (Paragraph&{type:"paragraph";});
export type NodeRoot = (Root&{type:"root";});
export type NodeStrong = (Strong&{type:"strong";});
export type NodeTable = (Table&{type:"table";});
export type NodeTableCell = (TableCell&{type:"tableCell";});
export type NodeTableRow = (TableRow&{type:"tableRow";});
export type NodeText = (Text&{type:"text";});
export type NodeThematicBreak = (ThematicBreak&{type:"thematicBreak";});
export type NodeToml = (Toml&{type:"toml";});
export type NodeTwoColumns = (TwoColumns&{type:"twoColumns";});
export type NodeYaml = (Yaml&{type:"yaml";});
export type Paragraph = {children:Node[];};
export type PostDataReturn = {id:number;};
export type ProblemKind = ("Interactive"|"SubmitAnswer"|{Traditional:IOKind;});
export type ProfileQuery = {username:Username;};
export type ReferenceKind = (ReferenceKindCollapsed|ReferenceKindFull|ReferenceKindShortcut);
export type ReferenceKindCollapsed = "collapsed";
export type ReferenceKindFull = "full";
export type ReferenceKindShortcut = "shortcut";
export type RegisterPayload = {email:string;passwordHash:string;username:Username;};
export type Root = {children:Node[];};
export type Statement = {meta:StmtMeta;statement:Node;};
export type StmtMeta = {kind:(ProblemKind|null);memory:(Memory|null);time:(Elapse|null);title:string;};
export type StmtQuery = {id:number;};
export type Strong = {children:Node[];};
export type Table = {align:AlignKind[];children:Node[];};
export type TableCell = {children:Node[];};
export type TableRow = {children:Node[];};
export type Text = {value:string;};
export type ThematicBreak = {};
export type Toml = {value:string;};
export type TwoColumns = {left:Node;right:Node;};
export type UserDisplayInfo = {email:string;gender:number;id:number;motto:string;name:string;register_time:string;username:Username;};
export type UserEditInfo = {email:string;gender:number;id:number;motto:string;name:string;register_time:string;username:string;};
export type UserUpdateInfo = {email:(null|string);gender:(null|number);motto:(null|string);name:(null|string);password_hash:(null|string);};
export type Username = string;
export type Yaml = {value:string;};
export function useAPI () { return { auth: { login: { post: (payload: AuthLoginPostPayload) => callAPI("post", "/auth/login", payload) as Promise<AsyncData<void, FetchError>>,
 },
logout: { post: () => callAPI("post", "/auth/logout") as Promise<AsyncData<void, FetchError>>,
 },
register: { post: (payload: AuthRegisterPostPayload) => callAPI("post", "/auth/register", payload) as Promise<AsyncData<void, FetchError>>,
 },
info: { get: () => callAPI("get", "/auth/info") as Promise<AsyncData<AuthInfoGetReturn | null, FetchError>>,
 },
 },
user: { get: (payload: UserGetPayload) => callAPI("get", "/user", payload) as Promise<AsyncData<UserGetReturn | null, FetchError>>,
edit: { get: () => callAPI("get", "/user/edit") as Promise<AsyncData<UserEditGetReturn | null, FetchError>>,
post: (payload: UserEditPostPayload) => callAPI("post", "/user/edit", payload) as Promise<AsyncData<void, FetchError>>,
 },
gravatar: { get: (payload: UserGravatarGetPayload) => callAPI("get", "/user/gravatar", payload) as Promise<AsyncData<void, FetchError>>,
 },
 },
problem: { full_dbg: { get: () => callAPI("get", "/problem/full_dbg") as Promise<AsyncData<ProblemFullDbgGetReturn | null, FetchError>>,
 },
metas: { get: (payload: ProblemMetasGetPayload) => callAPI("get", "/problem/metas", payload) as Promise<AsyncData<ProblemMetasGetReturn | null, FetchError>>,
 },
statement: { get: (payload: ProblemStatementGetPayload) => callAPI("get", "/problem/statement", payload) as Promise<AsyncData<ProblemStatementGetReturn | null, FetchError>>,
 },
fulldata: { post: (payload: ProblemFulldataPostPayload) => callAPI("post", "/problem/fulldata", payload) as Promise<AsyncData<ProblemFulldataPostReturn | null, FetchError>>,
 },
fulldata_meta: { get: (payload: ProblemFulldataMetaGetPayload) => callAPI("get", "/problem/fulldata_meta", payload) as Promise<AsyncData<ProblemFulldataMetaGetReturn | null, FetchError>>,
 },
 },
 }; }
export type AuthInfoGetReturn = AuthInfoRes;
export type AuthLoginPostPayload = LoginPayload;
export type AuthRegisterPostPayload = RegisterPayload;
export type ProblemFullDbgGetReturn = [number,StmtMeta][];
export type ProblemFulldataMetaGetPayload = FullDataMetaQuery;
export type ProblemFulldataMetaGetReturn = any;
export type ProblemFulldataPostPayload = FormData;
export type ProblemFulldataPostReturn = PostDataReturn;
export type ProblemMetasGetPayload = MetasQuery;
export type ProblemMetasGetReturn = [number,StmtMeta][];
export type ProblemStatementGetPayload = StmtQuery;
export type ProblemStatementGetReturn = Statement;
export type UserEditGetReturn = UserEditInfo;
export type UserEditPostPayload = UserUpdateInfo;
export type UserGetPayload = ProfileQuery;
export type UserGetReturn = UserDisplayInfo;
export type UserGravatarGetPayload = GravatarInfo;

