[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
serde_derive = "1.0.154"
serde = "1.0.154"
email_address = "0.2.4"
serde_json = "1.0.94"
