[package]
name = "structural_macro_utils"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
version.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["parsing", "full", "extra-traits"] }
quote = "1.0"