[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["parsing", "full", "extra-traits"] }
quote = "1.0"

[dev-dependencies]
actix-web = "4"
