[package]
name = "problem"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
queues = "1.0.2"
serde = "1.0.152"
serde_derive = "1.0.152"
zip = "0.6.4"
sha2 = { version = "0.10", default-features = false }
derive_more = "0.99.17"
